// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagementSystem.Data;

#nullable disable

namespace Restaurant_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantManagementSystem.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Email = "ahmed.admin@gmail.com",
                            FirstName = "Ahmed",
                            LastName = "Ali",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("AdminId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AdminId = 1,
                            Category = "Burgers",
                            Description = "Beef burger with cheese and fresh vegetables",
                            ImageFileName = "classic_burger.png",
                            IsAvailable = true,
                            Name = "Classic Burger",
                            Price = 150m
                        },
                        new
                        {
                            ProductId = 2,
                            AdminId = 1,
                            Category = "Burgers",
                            Description = "Crispy chicken burger with special sauce",
                            ImageFileName = "chicken_burger.png",
                            IsAvailable = true,
                            Name = "Chicken Burger",
                            Price = 140m
                        },
                        new
                        {
                            ProductId = 3,
                            AdminId = 1,
                            Category = "Burgers",
                            Description = "Double beef burger with double cheese",
                            ImageFileName = "double_beef_burger.png",
                            IsAvailable = true,
                            Name = "Double Beef Burger",
                            Price = 220m
                        },
                        new
                        {
                            ProductId = 4,
                            AdminId = 1,
                            Category = "Pizza",
                            Description = "Pizza with tomato sauce and mozzarella cheese",
                            ImageFileName = "margherita_pizza.png",
                            IsAvailable = true,
                            Name = "Margherita Pizza",
                            Price = 180m
                        },
                        new
                        {
                            ProductId = 5,
                            AdminId = 1,
                            Category = "Pizza",
                            Description = "Pizza topped with chicken and vegetables",
                            ImageFileName = "chicken_pizza.png",
                            IsAvailable = true,
                            Name = "Chicken Pizza",
                            Price = 230m
                        },
                        new
                        {
                            ProductId = 6,
                            AdminId = 1,
                            Category = "Pizza",
                            Description = "Pizza with pepperoni and mozzarella cheese",
                            ImageFileName = "pepperoni_pizza.png",
                            IsAvailable = true,
                            Name = "Pepperoni Pizza",
                            Price = 250m
                        },
                        new
                        {
                            ProductId = 7,
                            AdminId = 1,
                            Category = "Pasta",
                            Description = "Creamy pasta with grilled chicken",
                            ImageFileName = "chicken_pasta.png",
                            IsAvailable = true,
                            Name = "Chicken Pasta",
                            Price = 170m
                        },
                        new
                        {
                            ProductId = 8,
                            AdminId = 1,
                            Category = "Pasta",
                            Description = "Pasta with creamy Alfredo sauce",
                            ImageFileName = "alfredo_pasta.png",
                            IsAvailable = true,
                            Name = "Alfredo Pasta",
                            Price = 160m
                        },
                        new
                        {
                            ProductId = 9,
                            AdminId = 1,
                            Category = "Sandwiches",
                            Description = "Grilled chicken sandwich with vegetables",
                            ImageFileName = "chicken_sandwich.png",
                            IsAvailable = true,
                            Name = "Chicken Sandwich",
                            Price = 120m
                        },
                        new
                        {
                            ProductId = 10,
                            AdminId = 1,
                            Category = "Sandwiches",
                            Description = "Crispy chicken with special sauce",
                            ImageFileName = "crispy_chicken_sandwich.png",
                            IsAvailable = true,
                            Name = "Crispy Chicken Sandwich",
                            Price = 130m
                        },
                        new
                        {
                            ProductId = 11,
                            AdminId = 1,
                            Category = "Sides",
                            Description = "Crispy golden french fries",
                            ImageFileName = "french_fries.png",
                            IsAvailable = true,
                            Name = "French Fries",
                            Price = 60m
                        },
                        new
                        {
                            ProductId = 12,
                            AdminId = 1,
                            Category = "Sides",
                            Description = "French fries topped with melted cheese",
                            ImageFileName = "cheese_fries.png",
                            IsAvailable = true,
                            Name = "Cheese Fries",
                            Price = 85m
                        },
                        new
                        {
                            ProductId = 13,
                            AdminId = 1,
                            Category = "Meals",
                            Description = "Chicken, fries and soft drink",
                            ImageFileName = "chicken_meal.png",
                            IsAvailable = true,
                            Name = "Chicken Meal",
                            Price = 260m
                        },
                        new
                        {
                            ProductId = 14,
                            AdminId = 1,
                            Category = "Meals",
                            Description = "Beef burger, fries and soft drink",
                            ImageFileName = "beef_meal.png",
                            IsAvailable = true,
                            Name = "Beef Meal",
                            Price = 280m
                        },
                        new
                        {
                            ProductId = 15,
                            AdminId = 1,
                            Category = "Drinks",
                            Description = "Cold soft drink",
                            ImageFileName = "cola.png",
                            IsAvailable = true,
                            Name = "Cola",
                            Price = 50m
                        },
                        new
                        {
                            ProductId = 16,
                            AdminId = 1,
                            Category = "Drinks",
                            Description = "Fresh orange juice",
                            ImageFileName = "orange_juice.png",
                            IsAvailable = true,
                            Name = "Orange Juice",
                            Price = 70m
                        },
                        new
                        {
                            ProductId = 17,
                            AdminId = 1,
                            Category = "Drinks",
                            Description = "Fresh strawberry juice",
                            ImageFileName = "strawberry_juice.png",
                            IsAvailable = true,
                            Name = "Strawberry Juice",
                            Price = 80m
                        },
                        new
                        {
                            ProductId = 18,
                            AdminId = 1,
                            Category = "Desserts",
                            Description = "Chocolate cake with chocolate sauce",
                            ImageFileName = "chocolate_cake.png",
                            IsAvailable = true,
                            Name = "Chocolate Cake",
                            Price = 100m
                        },
                        new
                        {
                            ProductId = 19,
                            AdminId = 1,
                            Category = "Desserts",
                            Description = "Classic creamy cheesecake",
                            ImageFileName = "cheesecake.png",
                            IsAvailable = true,
                            Name = "Cheesecake",
                            Price = 110m
                        },
                        new
                        {
                            ProductId = 20,
                            AdminId = 1,
                            Category = "Desserts",
                            Description = "Three scoops of vanilla ice cream",
                            ImageFileName = "ice_cream.png",
                            IsAvailable = true,
                            Name = "Ice Cream",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Order", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagementSystem.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Product", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
