// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagementSystem.Data;

#nullable disable

namespace Restaurant_Management_System.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816150231_AddRestaurantEntities")]
    partial class AddRestaurantEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantManagementSystem.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Email = "ahmed.admin@gmail.com",
                            FirstName = "Ahmed",
                            LastName = "Ali",
                            Password = "123456",
                            Role = "Admin"
                        },
                        new
                        {
                            AdminId = 2,
                            Email = "mona.admin@gmail.com",
                            FirstName = "Mona",
                            LastName = "Hassan",
                            Password = "123456",
                            Role = "Admin"
                        },
                        new
                        {
                            AdminId = 3,
                            Email = "omar.admin@gmail.com",
                            FirstName = "Omar",
                            LastName = "Mohamed",
                            Password = "123456",
                            Role = "Manager"
                        },
                        new
                        {
                            AdminId = 4,
                            Email = "sara.admin@gmail.com",
                            FirstName = "Sara",
                            LastName = "Ahmed",
                            Password = "123456",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            City = "Damietta",
                            Email = "mazen@gmail.com",
                            FirstName = "Mazen",
                            LastName = "Ahmed",
                            Phone = "01000000001",
                            Street = "El Bahr Street",
                            ZipCode = "34511"
                        },
                        new
                        {
                            CustomerID = 2,
                            City = "Cairo",
                            Email = "mohamed@gmail.com",
                            FirstName = "Mohamed",
                            LastName = "Ali",
                            Phone = "01000000002",
                            Street = "Nile Street",
                            ZipCode = "11511"
                        },
                        new
                        {
                            CustomerID = 3,
                            City = "Damietta",
                            Email = "sara@gmail.com",
                            FirstName = "Sara",
                            LastName = "Hassan",
                            Phone = "01000000003",
                            Street = "Port Said Street",
                            ZipCode = "34512"
                        },
                        new
                        {
                            CustomerID = 4,
                            City = "Mansoura",
                            Email = "youssef@gmail.com",
                            FirstName = "Youssef",
                            LastName = "Mahmoud",
                            Phone = "01000000004",
                            Street = "El Geish Street",
                            ZipCode = "35511"
                        },
                        new
                        {
                            CustomerID = 5,
                            City = "Cairo",
                            Email = "nour@gmail.com",
                            FirstName = "Nour",
                            LastName = "Khaled",
                            Phone = "01000000005",
                            Street = "El Nasr Street",
                            ZipCode = "11765"
                        },
                        new
                        {
                            CustomerID = 6,
                            City = "Mansoura",
                            Email = "omar@gmail.com",
                            FirstName = "Omar",
                            LastName = "Tarek",
                            Phone = "01000000006",
                            Street = "University Street",
                            ZipCode = "35516"
                        },
                        new
                        {
                            CustomerID = 7,
                            City = "Damietta",
                            Email = "hana@gmail.com",
                            FirstName = "Hana",
                            LastName = "Samir",
                            Phone = "01000000007",
                            Street = "Corniche Street",
                            ZipCode = "34513"
                        },
                        new
                        {
                            CustomerID = 8,
                            City = "Cairo",
                            Email = "karim@gmail.com",
                            FirstName = "Karim",
                            LastName = "Mostafa",
                            Phone = "01000000008",
                            Street = "Tahrir Street",
                            ZipCode = "11512"
                        },
                        new
                        {
                            CustomerID = 9,
                            City = "Alexandria",
                            Email = "laila@gmail.com",
                            FirstName = "Laila",
                            LastName = "Ayman",
                            Phone = "01000000009",
                            Street = "Gardenia Street",
                            ZipCode = "21500"
                        },
                        new
                        {
                            CustomerID = 10,
                            City = "Alexandria",
                            Email = "adam@gmail.com",
                            FirstName = "Adam",
                            LastName = "Hany",
                            Phone = "01000000010",
                            Street = "Saad Zaghloul Street",
                            ZipCode = "21501"
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 300m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing",
                            TotalAmount = 370m
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 270m
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalAmount = 400m
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 280m
                        },
                        new
                        {
                            OrderId = 6,
                            CustomerId = 6,
                            OrderDate = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing",
                            TotalAmount = 330m
                        },
                        new
                        {
                            OrderId = 7,
                            CustomerId = 7,
                            OrderDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 360m
                        },
                        new
                        {
                            OrderId = 8,
                            CustomerId = 8,
                            OrderDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            TotalAmount = 220m
                        },
                        new
                        {
                            OrderId = 9,
                            CustomerId = 9,
                            OrderDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 450m
                        },
                        new
                        {
                            OrderId = 10,
                            CustomerId = 10,
                            OrderDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalAmount = 300m
                        },
                        new
                        {
                            OrderId = 11,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 430m
                        },
                        new
                        {
                            OrderId = 12,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Preparing",
                            TotalAmount = 320m
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            SubTotal = 300m,
                            UnitPrice = 150m
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 1,
                            SubTotal = 230m,
                            UnitPrice = 230m
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 11,
                            Quantity = 1,
                            SubTotal = 60m,
                            UnitPrice = 60m
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 15,
                            Quantity = 1,
                            SubTotal = 50m,
                            UnitPrice = 50m
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 20,
                            Quantity = 1,
                            SubTotal = 30m,
                            UnitPrice = 30m
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 2,
                            Quantity = 1,
                            SubTotal = 140m,
                            UnitPrice = 140m
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 11,
                            Quantity = 1,
                            SubTotal = 60m,
                            UnitPrice = 60m
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 17,
                            Quantity = 1,
                            SubTotal = 70m,
                            UnitPrice = 70m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 1,
                            SubTotal = 250m,
                            UnitPrice = 250m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 12,
                            Quantity = 1,
                            SubTotal = 85m,
                            UnitPrice = 85m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 15,
                            Quantity = 1,
                            SubTotal = 50m,
                            UnitPrice = 50m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 18,
                            Quantity = 1,
                            SubTotal = 15m,
                            UnitPrice = 15m
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 14,
                            Quantity = 1,
                            SubTotal = 280m,
                            UnitPrice = 280m
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = 13,
                            Quantity = 1,
                            SubTotal = 260m,
                            UnitPrice = 260m
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = 15,
                            Quantity = 1,
                            SubTotal = 50m,
                            UnitPrice = 50m
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = 11,
                            Quantity = 1,
                            SubTotal = 20m,
                            UnitPrice = 20m
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = 3,
                            Quantity = 1,
                            SubTotal = 220m,
                            UnitPrice = 220m
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = 11,
                            Quantity = 1,
                            SubTotal = 60m,
                            UnitPrice = 60m
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = 17,
                            Quantity = 1,
                            SubTotal = 80m,
                            UnitPrice = 80m
                        },
                        new
                        {
                            OrderId = 8,
                            ProductId = 4,
                            Quantity = 1,
                            SubTotal = 180m,
                            UnitPrice = 180m
                        },
                        new
                        {
                            OrderId = 8,
                            ProductId = 15,
                            Quantity = 1,
                            SubTotal = 40m,
                            UnitPrice = 40m
                        },
                        new
                        {
                            OrderId = 9,
                            ProductId = 3,
                            Quantity = 1,
                            SubTotal = 220m,
                            UnitPrice = 220m
                        },
                        new
                        {
                            OrderId = 9,
                            ProductId = 7,
                            Quantity = 1,
                            SubTotal = 170m,
                            UnitPrice = 170m
                        },
                        new
                        {
                            OrderId = 9,
                            ProductId = 15,
                            Quantity = 1,
                            SubTotal = 50m,
                            UnitPrice = 50m
                        },
                        new
                        {
                            OrderId = 9,
                            ProductId = 18,
                            Quantity = 1,
                            SubTotal = 10m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = 5,
                            Quantity = 1,
                            SubTotal = 230m,
                            UnitPrice = 230m
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = 11,
                            Quantity = 1,
                            SubTotal = 60m,
                            UnitPrice = 60m
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = 15,
                            Quantity = 1,
                            SubTotal = 10m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            OrderId = 11,
                            ProductId = 3,
                            Quantity = 1,
                            SubTotal = 220m,
                            UnitPrice = 220m
                        },
                        new
                        {
                            OrderId = 11,
                            ProductId = 5,
                            Quantity = 1,
                            SubTotal = 230m,
                            UnitPrice = 230m
                        },
                        new
                        {
                            OrderId = 12,
                            ProductId = 7,
                            Quantity = 1,
                            SubTotal = 170m,
                            UnitPrice = 170m
                        },
                        new
                        {
                            OrderId = 12,
                            ProductId = 4,
                            Quantity = 1,
                            SubTotal = 180m,
                            UnitPrice = 180m
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("AdminId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AdminId = 1,
                            Category = "Burgers",
                            Description = "Beef burger with cheese and fresh vegetables",
                            IsAvailable = true,
                            Name = "Classic Burger",
                            Price = 150m
                        },
                        new
                        {
                            ProductId = 2,
                            AdminId = 1,
                            Category = "Burgers",
                            Description = "Crispy chicken burger with special sauce",
                            IsAvailable = true,
                            Name = "Chicken Burger",
                            Price = 140m
                        },
                        new
                        {
                            ProductId = 3,
                            AdminId = 2,
                            Category = "Burgers",
                            Description = "Double beef burger with double cheese",
                            IsAvailable = true,
                            Name = "Double Beef Burger",
                            Price = 220m
                        },
                        new
                        {
                            ProductId = 4,
                            AdminId = 2,
                            Category = "Pizza",
                            Description = "Pizza with tomato sauce and mozzarella cheese",
                            IsAvailable = true,
                            Name = "Margherita Pizza",
                            Price = 180m
                        },
                        new
                        {
                            ProductId = 5,
                            AdminId = 2,
                            Category = "Pizza",
                            Description = "Pizza topped with chicken and vegetables",
                            IsAvailable = true,
                            Name = "Chicken Pizza",
                            Price = 230m
                        },
                        new
                        {
                            ProductId = 6,
                            AdminId = 3,
                            Category = "Pizza",
                            Description = "Pizza with pepperoni and mozzarella cheese",
                            IsAvailable = true,
                            Name = "Pepperoni Pizza",
                            Price = 250m
                        },
                        new
                        {
                            ProductId = 7,
                            AdminId = 3,
                            Category = "Pasta",
                            Description = "Creamy pasta with grilled chicken",
                            IsAvailable = true,
                            Name = "Chicken Pasta",
                            Price = 170m
                        },
                        new
                        {
                            ProductId = 8,
                            AdminId = 3,
                            Category = "Pasta",
                            Description = "Pasta with creamy Alfredo sauce",
                            IsAvailable = true,
                            Name = "Alfredo Pasta",
                            Price = 160m
                        },
                        new
                        {
                            ProductId = 9,
                            AdminId = 1,
                            Category = "Sandwiches",
                            Description = "Grilled chicken sandwich with vegetables",
                            IsAvailable = true,
                            Name = "Chicken Sandwich",
                            Price = 120m
                        },
                        new
                        {
                            ProductId = 10,
                            AdminId = 1,
                            Category = "Sandwiches",
                            Description = "Crispy chicken with special sauce",
                            IsAvailable = true,
                            Name = "Crispy Chicken Sandwich",
                            Price = 130m
                        },
                        new
                        {
                            ProductId = 11,
                            AdminId = 2,
                            Category = "Sides",
                            Description = "Crispy golden french fries",
                            IsAvailable = true,
                            Name = "French Fries",
                            Price = 60m
                        },
                        new
                        {
                            ProductId = 12,
                            AdminId = 2,
                            Category = "Sides",
                            Description = "French fries topped with melted cheese",
                            IsAvailable = true,
                            Name = "Cheese Fries",
                            Price = 85m
                        },
                        new
                        {
                            ProductId = 13,
                            AdminId = 3,
                            Category = "Meals",
                            Description = "Chicken, fries and soft drink",
                            IsAvailable = true,
                            Name = "Chicken Meal",
                            Price = 260m
                        },
                        new
                        {
                            ProductId = 14,
                            AdminId = 3,
                            Category = "Meals",
                            Description = "Beef burger, fries and soft drink",
                            IsAvailable = true,
                            Name = "Beef Meal",
                            Price = 280m
                        },
                        new
                        {
                            ProductId = 15,
                            AdminId = 4,
                            Category = "Drinks",
                            Description = "Cold soft drink",
                            IsAvailable = true,
                            Name = "Cola",
                            Price = 50m
                        },
                        new
                        {
                            ProductId = 16,
                            AdminId = 4,
                            Category = "Drinks",
                            Description = "Fresh orange juice",
                            IsAvailable = true,
                            Name = "Orange Juice",
                            Price = 70m
                        },
                        new
                        {
                            ProductId = 17,
                            AdminId = 4,
                            Category = "Drinks",
                            Description = "Fresh mango juice",
                            IsAvailable = true,
                            Name = "Mango Juice",
                            Price = 80m
                        },
                        new
                        {
                            ProductId = 18,
                            AdminId = 4,
                            Category = "Desserts",
                            Description = "Chocolate cake with chocolate sauce",
                            IsAvailable = true,
                            Name = "Chocolate Cake",
                            Price = 100m
                        },
                        new
                        {
                            ProductId = 19,
                            AdminId = 4,
                            Category = "Desserts",
                            Description = "Classic creamy cheesecake",
                            IsAvailable = true,
                            Name = "Cheesecake",
                            Price = 110m
                        },
                        new
                        {
                            ProductId = 20,
                            AdminId = 4,
                            Category = "Desserts",
                            Description = "Three scoops of vanilla ice cream",
                            IsAvailable = true,
                            Name = "Ice Cream",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Order", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagementSystem.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Product", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
